import Head from 'next/head';
import { Box, Flex, Input } from '@mantine/core';

import { BiSearchAlt2 } from 'react-icons/bi';
import QuicksButton from '@/components/QuicksButton';

export default function Home() {
  return (
    <>
      <Head>
        <title>Simple Quick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          backgroundColor: '#333',
        }}
      >
        <Box
          ml={250}
          pos={'relative'}
          sx={{
            borderLeft: '1px gray solid',
            minHeight: '100vh',
            backgroundColor: '#333',
          }}
        >
          <Input
            bg={'#000'}
            radius={'none'}
            disabled
            icon={<BiSearchAlt2 size="1rem" color="white" />}
          />

          {/* Quicks Button */}
          <Box pos={'absolute'} bottom={27} right={34}>
            <Flex gap={10}>
              <QuicksButton />
            </Flex>
          </Box>
        </Box>
      </Box>
    </>
  );
}
